### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by fommil**
Work in Progress to address #67

Raising as PR so I get access to the test runners on travis.

Since this bug only exhibits itself on Windows, I'm going to set up an appveyor build. Can somebody please add this repo to appveyor?

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @fommil,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by fommil** [comment]
For the avoidance of doubt, I do **not** agree to sign this CLA. I only agree to release this software under the Modified BSD 2 Clause licence and I retain full copyright on my works.

**Comment by typesafehub-validator** [comment]
Hi @fommil,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by fommil** [comment]
ok, I have a reproduction! But I'm doing it in my `master` build so that I can use appveyor, and also because this annoying CLA checker keeps spamming me every time I push onto the PR.

**Comment by fommil** [comment]
travis keeps crashing. I have no idea why.

**Comment by fommil** [comment]
I'm closing this and the original ticket as I'm not pretty convinced that it is a JVM bug that can only be worked around in sbt itself, not the junit-interface.

**Pull request closed without merging**
