### PR TITLE
Update sbt to version 0.13.11

### PR DESCRIPTION
**Pull request by VEINHORN**

### CODE REVIEW

**Comment by SethTisue** [comment]
this seems to have been forgotten about — if you rebased against current master, maybe we could get a maintainer's attention

**Comment by benmccann** [comment]
@VEINHORN please rebase this and ping me and I'll merge it for you

**Comment by SethTisue** [comment]
note that sbt is at 0.13.13 these days

**Comment by benmccann** [comment]
sbt has been upgraded to 0.13.13: https://github.com/sbt/junit-interface/commit/ab93b7aab8eed820c6d690a9f77e1c6883b9d28f

**Pull request closed without merging**
