### PR TITLE
Get Travis working

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by szeiger** [comment]
Does the caching give us any performance advantage? When I tried it in the Slick build it didn't make a difference. There seems to be an upstream cache anyway so that resolving is fast.

**Comment by dwijnand** [comment]
The benefit is in not needing to update the cache every time for useless, noisy changes, only updating dependency versions or sbt version. I've never fully tested it to be honest, and also things change over time.

**Comment by SethTisue** [comment]
I have found enabling the caching feature to be a noticeable speed benefit in a variety of other repos.

**Comment by SethTisue** [comment]
otoh, in a small repo like this it probably doesn't matter much either way.

**Comment by dwijnand** [comment]
Well it's done, and it's a small change. Not sure if you're exactly contesting it or not, but I'm happy to drop it if preferred, no sweat.

**Comment by SethTisue** [comment]
I'd be fine merging as-is, but I'll let @szeiger make the call.

**Comment by szeiger** [comment]
I don't have a strong opinion. I've neither seen substantial performance improvements nor problems caused by caching. Let's give it a try.

**Comment by SethTisue** [comment]
thank you Dale!

**Comment by dwijnand** [comment]
No worries. Thanks for the merge.

**Pull request merged**
